spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9094
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: mail-service